using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject: Lightweight dependency injection for .NET")]
[assembly: AssemblyCompanyAttribute("Enkari, Ltd.")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007-2011 Enkari, Ltd. and contributors")]
[assembly: AssemblyVersionAttribute("3.0.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.1.0")]
#if !PCL
[assembly: ComVisibleAttribute(false)]
#endif
[assembly: CLSCompliantAttribute(true)]

