using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject: Lightweight dependency injection for .NET")]
[assembly: AssemblyCompanyAttribute("Enkari, Ltd.")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007-2009 Enkari, Ltd. and contributors")]
[assembly: AssemblyVersionAttribute("2.0.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

